apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:10.4
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: letsforget
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432

          
