import { PostPlaceRequestDto } from "@lets-forget/backend/src/modules/place/dto/PostPlaceRequest.dto";

export const places: PostPlaceRequestDto[] = [
    {
        cityId: 'Warsaw',
        name: 'Executive Lounge Browary Warszawskie',
        street: 'Krochmalna',
        streetNumber: '59/U3',
        latitude: 52.235801,
        longitude: 20.987484,
    },
    {
        cityId: 'Warsaw',
        name: 'Browar Warszawski Restauracja Grill i Bar',
        street: 'Haberbuscha i Schielego',
        streetNumber: '2',
        latitude: 52.235042,
        longitude: 20.987534,
    },
    {
        cityId: 'Warsaw',
        name: 'Bar a Boo Warszawa',
        street: 'plac Europejski',
        streetNumber: '5',
        latitude: 52.232762,
        longitude: 20.985131,
    },
    {
        cityId: 'Warsaw',
        name: 'Piano Bar Warsaw',
        street: 'Żelazna',
        streetNumber: '51/53/Budynek 26',
        latitude: 52.232424,
        longitude: 20.992194,
    },
    {
        cityId: 'Warsaw',
        name: 'FoodTown Bars',
        street: 'Żelazna',
        streetNumber: '51/53',
        latitude: 52.232227,
        longitude: 20.990199,
    },
    {
        cityId: 'Warsaw',
        name: 'Cafe - bar Paragraf',
        street: 'aleja Solidarności',
        streetNumber: '84',
        latitude: 52.242040,
        longitude: 20.991666,
    },
    {
        cityId: 'Warsaw',
        name: 'Niewinność Wine Bar',
        street: 'plac Żelaznej Bramy',
        streetNumber: '1',
        latitude: 52.239531,
        longitude: 20.999794,
    },
    {
        cityId: 'Warsaw',
        name: 'Bar Studio',
        street: 'plac Defilad',
        streetNumber: '1',
        latitude: 52.232525,
        longitude: 21.006828,
    },
    {
        cityId: 'Warsaw',
        name: 'Panorama Sky Bar',
        street: 'al. Jerozolimskie',
        streetNumber: '65/79',
        latitude: 52.228044,
        longitude: 21.004990,
    },
    {
        cityId: 'Warsaw',
        name: 'Bar Pacyfik',
        street: 'Hoża',
        streetNumber: '61',
        latitude: 52.224959,
        longitude:  21.007791,
    },
    {
        cityId: 'Warsaw',
        name: 'Zebra SHOT BAR',
        street: 'Nowogrodzka',
        streetNumber: '22',
        latitude: 52.229968,
        longitude: 21.013787,
    },
    {
        cityId: 'Warsaw',
        name: 'Bar Norka',
        street: 'Nowogrodzka',
        streetNumber: '16',
        latitude: 52.229581,
        longitude: 21.015401,
    },
    {
        cityId: 'Warsaw',
        name: 'Bar 13',
        street: 'Bracka',
        streetNumber: '9',
        latitude: 52.230536,
        longitude: 21.019013,
    },
    {
        cityId: 'Warsaw',
        name: 'Zagrywki',
        street: 'Nowy Świat',
        streetNumber: '4A',
        latitude: 52.230570,
        longitude: 21.022131,
    },
    {
        cityId: 'Warsaw',
        name: 'Zamieszanie - cocktail bar',
        street: 'Nowy Świat',
        streetNumber: '6/12',
        latitude: 52.231535,
        longitude:  21.022171,
    },
    {
        cityId: 'Warsaw',
        name: 'Weles Bar',
        street: 'Nowogrodzka',
        streetNumber: '11',
        latitude: 52.229482,
        longitude: 21.017679,
    },
    {
        cityId: 'Warsaw',
        name: 'Coctail Bar Max & Dom Whisky',
        street: 'Nowy Świat',
        streetNumber: '32',
        latitude: 52.233634,
        longitude: 21.019544,
    },
    {
        cityId: 'Warsaw',
        name: 'Komix - Pawilony Nowy Świat',
        street: 'Nowy Świat',
        streetNumber: '22/28',
        latitude: 52.233114,
        longitude: 21.020296,
    },
    {
        cityId: 'Warsaw',
        name: 'Babajaga - Cocktail Bar',
        street: 'Nowy Świat',
        streetNumber: '22/28',
        latitude: 52.233124,
        longitude: 21.020297,
    },
    {
        cityId: 'Warsaw',
        name: 'Ginger Pub - Pawilony Nowy Świat',
        street: 'Nowy Świat',
        streetNumber: '22/28',
        latitude: 52.233012,
        longitude: 21.020361,
    },
    {
        cityId: 'Warsaw',
        name: 'Cynamon Pub',
        street: 'Nowy Świat',
        streetNumber: '22/28',
        latitude: 52.233171,
        longitude: 21.020621,
    },
    {
        cityId: 'Warsaw',
        name: 'Kufle i Kapsle Nowy Świat',
        street: 'Nowy Świat',
        streetNumber: '27',
        latitude: 52.232974,
        longitude: 21.019433,
    },
    {
        cityId: 'Warsaw',
        name: 'In Side',
        street: 'Nowy Świat',
        streetNumber: '27',
        latitude: 52.232692,
        longitude: 21.018948,
    },
    {
        cityId: 'Warsaw',
        name: 'Cybermachina Warszawa',
        street: 'Nowy Świat',
        streetNumber: '54/56',
        latitude: 52.235101,
        longitude: 21.018843,
    },
    {
        cityId: 'Warsaw',
        name: 'HOPSTER by Norka',
        street: 'Nowy Świat',
        streetNumber: '53',
        latitude: 52.235891,
        longitude: 21.018077,
    },
    {
        cityId: 'Warsaw',
        name: 'Retro Praga',
        street: 'Ząbkowska',
        streetNumber: '2',
        latitude: 52.252587,
        longitude: 21.038296,
    },
    {
        cityId: 'Warsaw',
        name: 'Łysy Pingwin',
        street: 'Ząbkowska',
        streetNumber: '11',
        latitude: 52.25356,
        longitude: 21.039961,
    },
    {
        cityId: 'Warsaw',
        name: 'Podwale Bar and Books',
        street: 'Wąski Dunaj',
        streetNumber: '20',
        latitude: 52.249354,
        longitude: 21.009821,
    },
    {
        cityId: 'Warsaw',
        name: 'Nowe Miasto Varsovia',
        street: 'Freta',
        streetNumber: '44/46',
        latitude: 52.253187,
        longitude: 21.007402,
    },
    {
        cityId: 'Warsaw',
        name: 'Elephant Belgian Pub',
        street: 'Freta',
        streetNumber: '19',
        latitude: 52.251960,
        longitude: 21.007936,
    },
    {
        cityId: 'Warsaw',
        name: 'Craft Beer Muranów - Piwny Świat',
        street: 'Gen. W. Andersa',
        streetNumber: '23',
        latitude: 52.251129,
        longitude: 20.997954,
    },
    {
        cityId: 'Warsaw',
        name: 'Kufle i Kapsle Żoliborz',
        street: 'Księdza Jerzego Popiełuszki',
        streetNumber: '21',
        latitude: 52.270276,
        longitude: 20.973988,
    },
    {
        cityId: 'Warsaw',
        name: 'Pub Student',
        street: 'Ludwika Waryńskiego',
        streetNumber: '12',
        latitude: 52.216725,
        longitude: 21.016263,
    },
    {
        cityId: 'Warsaw',
        name: 'Zielona Gęś',
        street: 'al. Niepodległości',
        streetNumber: '177',
        latitude: 52.210863,
        longitude: 21.006449,
    },
];